maciejhirsz/logos

Cargo.lock, README.md, logos-derive/src/generator.rs, logos-derive/src/handlers.rs, logos-derive/src/lib.rs, logos-derive/src/regex.rs, logos-derive/src/tree.rs, logos/Cargo.toml, logos/src/lexer.rs, logos/src/lib.rs, tests/tests/lib.rs
+ [x] Support for the `+` regex flag.
+ [x] Allow for regex starting with the same prefix to blend (`0x` and `0b`).
=> Regex improvements

Cargo.lock, logos-derive/Cargo.toml, logos-derive/src/generator.rs, logos-derive/src/handlers.rs, logos-derive/src/lib.rs, logos-derive/src/regex.rs, logos-derive/src/tree.rs, logos-derive/src/util.rs, logos/Cargo.toml, logos/benches/bench.rs, logos/tests/lib.rs
+ [x] Using `regex_syntax` for parsing.
+ [x] Support for alternate `|` operator.
+ [x] Support for maybe `?` operator.
+ [x] Support for groups `()`.
=> Refactoring regex

.travis.yml, README.md, logos-derive/src/generator.rs, logos-derive/src/lib.rs, logos-derive/src/util.rs, logos/src/internal.rs, logos/src/lexer.rs, logos/src/lib.rs, test.sh, tests/tests/lib.rs
The last two features needed for Ratel and Lunarity!
=> [WIP] Adding support for `#[extras]` and `#[callback]`

Cargo.lock, tests/tests/advanced.rs, tests/tests/properties.rs
=> Tests for regex with properties

logos-derive/Cargo.toml, logos-derive/src/tree.rs, logos/Cargo.toml, tests/tests/advanced.rs
=> Fix collapsing of `Maybe` forks

Cargo.lock, logos-derive/Cargo.toml, logos-derive/src/tree.rs, tests/tests/simple.rs
Found a new edge case that breaks down in Lunarity after recent changes.
=> Fix regex alternates producing Maybe forks

Cargo.lock, README.md, logos-derive/Cargo.toml, logos-derive/src/generator.rs, logos-derive/src/handlers.rs, logos-derive/src/lib.rs, logos-derive/src/regex.rs, logos-derive/src/tree.rs, logos/Cargo.toml, logos/src/lib.rs, tests/Cargo.toml, tests/benches/bench.rs, tests/tests/advanced.rs, tests/tests/properties.rs, tests/tests/simple.rs
=> Edition 2018 + fixes

Cargo.lock, logos-derive/Cargo.toml, logos-derive/src/tree.rs, tests/tests/advanced.rs
=> Allow intersections on finite `Maybe` forks.

tests/tests/advanced.rs
This is another corner case.
I think if you want to take time and redesign branching algorithm from scratch then it is fine by me 
to wait longer with the fix.  However it seems like fixing this case should already prevent a large 
class of future bugs, as this is pretty much the last bug standing in my lexer, so hotfix is also worth considering :-)
=> Another fork corner case

Cargo.lock, logos-derive/Cargo.toml, logos-derive/src/generator.rs, logos-derive/src/lib.rs, logos/Cargo.toml, logos/src/internal.rs, logos/src/lexer.rs, logos/src/lib.rs, logos/src/source.rs, tests/benches/bench.rs, tests/tests/advanced.rs, tests/tests/simple.rs
=> Multi byte reads

logos-derive/Cargo.toml, logos-derive/src/generator.rs
=> Fix stack overflow in code generation

logos-derive/src/lib.rs, logos/src/lib.rs
=> Use const let for lookup! macro

README.md
README logo is not currently displaying ...
=> Fix logos logo

tests/tests/lexer_modes.rs
Now, if i run `cargo run`, it failed.
I fixed it.
=> runnable `cargo test`

Cargo.lock, logos-derive/Cargo.toml, logos-derive/src/graph/mod.rs, logos-derive/src/graph/regex.rs, logos/Cargo.toml, tests/tests/crunch.rs
Fixes #95, should also fix #97.
=> Fix merging rules

Cargo.lock, logos-derive/Cargo.toml, logos-derive/src/lib.rs, logos/Cargo.toml, logos/src/source.rs, tests/Cargo.toml
+ Bumped versions.
+ Removed the unused `Split` trait.
=> 0.10.0 release cleanup

Cargo.lock, logos-derive/Cargo.toml, logos-derive/src/generator/context.rs, logos-derive/src/generator/fork.rs, logos-derive/src/generator/mod.rs, logos-derive/src/graph/meta.rs, logos-derive/src/graph/mod.rs, logos-derive/src/graph/range.rs, logos-derive/src/lib.rs, logos/Cargo.toml, logos/src/internal.rs, logos/src/lexer.rs, logos/src/source.rs, tests/src/lib.rs, tests/tests/edgecase.rs
=> Fix too eager reads

logos-derive/src/graph/regex.rs, tests/tests/edgecase.rs
Fixes one of the issues in #132.
=> Fix loops in loops

logos/src/lexer.rs, logos/src/lib.rs, tests/src/lib.rs
Solves #153.
This PR will need a semver bump, since these are breaking changes.
=> Allow non-Default extras

logos-derive/src/parser/subpattern.rs, tests/tests/advanced.rs
Implemented based on the discussion from #162.
=> Add basic support for nested subpatterns.

logos-codegen/src/mir.rs, tests/tests/lexer_modes.rs
This PR provides support for regex repetition ranges
=> Add {n,m} repetition range support

logos/src/lexer.rs
Closes #231, closes #266.
Note to self: acknowledge @simvux for #231 in release notes.
=> Impl Deref and DerefMut for SpannedIter

Cargo.toml, logos-cli/Cargo.toml, logos-codegen/Cargo.toml, logos-codegen/src/lib.rs, logos-codegen/src/parser/mod.rs, logos-codegen/src/parser/type_params.rs, logos-derive/Cargo.toml, logos/Cargo.toml
Closes #288.
TODO:
+ [x] Still bunch of errors on meta parsing in `logos-codegen/src/lib.rs`.
+ [x] Verify that it all still works.
=> Update syn to 2.0

.github/workflows/rustbench.yml
=> chore(ci): print benchmarks to github step summary when fail to comment

examples/extras.rs, examples/json.rs, examples/json_borrowed.rs
=> chore(docs): cleanup examples

.pre-commit-config.yaml
=> chore: drop python linting frmo pre-commit-config

book/src/examples/json.md, book/src/examples/json_borrowed.md, examples/json.rs, examples/json_borrowed.rs
=> fix: fixed regex for string value in json examples

.github/workflows/coverage.yml, .github/workflows/pages.yml, .github/workflows/rustbench.yml, .github/workflows/rustlib.yml, .github/workflows/rustmsrv.yml, Cargo.toml, README.md, tests/Cargo.toml, tests/benches/bench.rs
`cargo msrv` should have fixed this issue. Moreover, we test that everything works as expected for CodeCov and CodSpeed actions.
=> chore(ci): `cargo msrv` and ci
