- Cargo.lock
- README.md
- logos-derive/Cargo.toml
- logos-derive/src/generator.rs
- logos-derive/src/lib.rs
- logos/Cargo.toml
- logos/src/lexer.rs
- logos/src/lib.rs
+ Using the closure syntax literal `|lex| { }` for handlers meant that the lookup table couldn't be made static, this is now fixed by explicitly using `fn` declarations.
+ `Logos::lexicon()` narrows the `&'static` lifetime to `&'a`, removing lifetime complaints form the Lexer.
Bonus points to @Vurich for figuring this out.
> Making the lookup table static

- Cargo.lock
- logos/Cargo.toml
- logos/src/lexer.rs
- logos/src/source.rs
- tests/tests/advanced.rs
- tests/tests/simple.rs
Closes #15 
This implements `Source` for raw byte slices `&[u8]`. The `Source` trait now, again, has an associated type `Slice` with a correct type of a slice.
This is a breaking change if you depended on using `&str` slices in callbacks. You can now instead use `Slice::as_bytes` to always get a `&[u8]` slice and work this way.
> Working on raw bytes

- Cargo.lock
- logos-derive/Cargo.toml
- logos-derive/src/generator.rs
- logos-derive/src/lib.rs
- logos-derive/src/regex.rs
- logos/src/lexer.rs
- logos/src/source.rs
- tests/tests/advanced.rs
As per suggestion in #22 Logos will use `utf8_ranges` crate to create branching for non-ASCII Unicode ranges.
> Full Unicode support!

- Cargo.lock
- logos-derive/Cargo.toml
- logos-derive/src/lib.rs
- logos-derive/src/util.rs
- logos/Cargo.toml
- logos/src/lib.rs
- tests/tests/advanced.rs
This adds a `lookup!` macro that can create static lookup tables matching token variants as indices to arbitrary static values.
> Crazy Lookup Table meta-macro hack!

- Cargo.lock
- logos-derive/Cargo.toml
- logos-derive/src/generator.rs
- logos-derive/src/lib.rs
- logos-derive/src/regex.rs
- logos-derive/src/tree.rs
- logos-derive/src/util.rs
- tests/tests/advanced.rs
- tests/tests/properties.rs
- tests/tests/simple.rs
This allows for defining callbacks per variant definition. Before you could write something like:
```rust
#[derive(Logos)]
enum Token {
// ...
#[token = "foo"]
#[regex = "bar"]
#[callback = "check_foo_or_bar"]
VariantWithCallback,
// ...
}
```
Which would invoke the `check_foo_or_bar()` callback on either `"foo"` or `"bar"` tokens. There was no way to differentiate between those, spare checking the token slice within the callback.
It's now possible to define callbacks per variant _definition_, not just enum variant itself:
```rust
#[derive(Logos)]
enum Token {
// ...
#[token("foo", callback = "check_foo")]
#[regex("bar", callback = "check_bar")]
VariantWithCallback,
// ...
}
```
This will invoke `check_foo()` only for `"foo"` tokens, and `check_bar()` only for `"bar"` tokens.
To make this …
> v0.8.0: Callbacks per definition

- tests/tests/advanced.rs
Unfortunately the ghost has returned, and simply adding another token 
```
#[token="~["]
Sglc
```
somehow messes up the tree structure, so that `LiteralUrbitAddress` which is branching off common point 
for `LiteralRelDate` is unrecognized again.
> Trigger fork bug again

- logos-derive/Cargo.toml
- logos-derive/src/tree.rs
- tests/benches/bench.rs
- tests/tests/advanced.rs
Fixes the issue detected with #49.
Moved the `is_finite` check from the entire fork to just the branch on which we test intersection prefixes, since that's the only case where we could get a stack overflow (by repeatedly unwinding an arm that ends with a `Repeat` fork).
CC @mikolajpp
> Fix intersection branching

- tests/tests/advanced.rs
I am quite sure I have seen this one before. 
The example is with quotes, but it should work with any character. 
In short, having tokens for `'` and `'''` makes it an error to parse `''` (double single quote) 
instead of returning two tokens corresponding to `'`.
> Quote fork bug

- logos/src/lexer.rs
- tests/tests/lexer_modes.rs
Relevant to #61, #27. Probably closes one or both of them.
Adds the capability for lexers to change the token type that they're lexing.
> Mighty Morphin Logos Lexer

- Cargo.lock
- README.md
- logos-derive/Cargo.toml
- logos-derive/src/generator/leaf.rs
- logos-derive/src/lib.rs
- logos/Cargo.toml
- logos/src/internal.rs
- logos/src/lib.rs
- tests/tests/callbacks.rs
+ Allows for enum variants to have types with lifetimes other than plain references, such as `(_, &'a str)` or `Cow<'a, str>` (closes #118).
+ Introduced `Filter<T>` enum, with `Emit(T)` and `Skip` variants, which allows callbacks to either produce a token with value `T`, or skip current match altogether (also #118).
> Container lifetimes

- logos-derive/src/error.rs
- logos-derive/src/generator/leaf.rs
- logos-derive/src/lib.rs
- logos-derive/src/parser.rs
- logos-derive/src/parsers.rs
- logos-derive/src/type_params.rs
- logos-derive/src/util.rs
- tests/tests/edgecase.rs
Deriving Logos on an enum with type parameters like so:
```rust
#[derive(Logos, Debug, PartialEq)]
enum Token<S, N> {
#[regex(r"[ \n\t\f]+", logos::skip)]
#[error]
Error,
#[regex("[a-z]+")]
Ident(S),
#[regex("[0-9]+", |lex| lex.slice().parse())]
Number(N)
}
```
Will now produce following errors:
```
error: Generic type parameter without a concrete type
Define a concrete type Logos can use: #[logos(type S = Type)]
--> tests/tests/edgecase.rs:339:16
|
339 |     enum Token<S, N> {
|                ^
error: Generic type parameter without a concrete type
Define a concrete type Logos can use: #[logos(type N = Type)]
--> tests/tests/edgecase.rs:339:19
|
339 |     enum Token<S, N> {
|                   ^
```
Defining concrete types for type parameters will make it work:
```rust
#[derive(Logos, …
```
> Handle type parameters

- logos-derive/src/parser/mod.rs
- logos-derive/src/parser/type_params.rs
- tests/tests/edgecase.rs
https://github.com/maciejhirsz/logos/pull/128 only replaced if the
parameter were a direct field in a variant. This extends it to work if
it is inside a tuple, argument to another type etc
> fix: Replace type parameters nested inside types

- logos-derive/src/lib.rs
- logos-derive/src/parser/definition.rs
- logos-derive/src/parser/mod.rs
- logos-derive/src/parser/subpattern.rs
- tests/tests/advanced.rs
Adds the ability to write `#[logos(subpattern name = r"regex")]` on the token enum, which is then used as a "subroutine" in regex rule definitions with the syntax `(?&name)`. Closes #109.
> Named subregex

- logos/src/lexer.rs
This method (no longer) exists, remove to avoid confusion.
> Remove reference to advance_as()

- logos-derive/src/generator/mod.rs
- logos-derive/src/graph/range.rs
- logos-derive/src/mir.rs
- logos-derive/src/parser/type_params.rs
- logos/src/source.rs
I couldn’t fix all of them, but I did fix thirteen of them. I’d recommend adding Clippy to CI to catch these early on.
> Fix a number of Clippy warnings

- README.md
- logos/src/lib.rs
The code to include the readme as a doctest is from [this cargo
ticket](https://github.com/rust-lang/cargo/issues/383#issuecomment-720873790).
> test readme & fix errors in readme examples

- Cargo.lock
- logos-derive/Cargo.toml
See: https://rustsec.org/advisories/RUSTSEC-2020-0122
> logos-derive: fix RUSTSEC-2020-0122 by upgrading beef: 0.4.1 -> 0.5.0

- .github/workflows/rust.yml
This shows errors from tests using the GitHub UI, rather than just giving you the text of the error.
> Use actions-rs/cargo instead of running cargo test manually

- logos-derive/src/lib.rs
- logos/src/lib.rs
- tests/tests/advanced.rs
This is entirely unused by logos's internals now, and is actually currently not correct in the face of explicit discriminants (as the discriminant of an enum variant can exceed `<Token as Logos>::SIZE`. Additionally, since we have to parse the explicit discriminant in a derive macro, said explicit discriminants are restricted to being literals, not expressions such as `u16::MAX`.
As support for `lookup!` tables is no longer necessary and is buggy and a cause of very inscrutable compiler errors (#192), I suggest that we just remove it, and suggest externals users use a different crate such as [`enum-map`](https://lib.rs/crates/enum-map) for equivalent functionality.
Fixes #192 (by removing the impacted code).
> Remove unused lookup! support

- logos-derive/src/lib.rs
- logos-derive/src/mir.rs
- logos-derive/src/parser/definition.rs
- logos-derive/src/parser/ignore_flags.rs
- logos-derive/src/parser/mod.rs
- tests/tests/ignore_case.rs
Issue: #196 
Case insensitivity is opt-in using the `ignore(...)` attribute.
```rust
#[derive(Logos)]
struct Token {
/* ... */
#[token("été", ignore(case))]
Ete,
#[token("DRôLE", ignore(ascii_case))]
Drole,
#[regex("[abc]+", ignore(case))]
Abc,
}
let mut lex = Token::lex("été ÉTÉ DrÔle Drôle AaabbCC");
assert_eq!((Some(Token::Ete), "été"), (lex.next(), lex.slice()));
assert_eq!((Some(Token::Ete), "ÉTÉ"), (lex.next(), lex.slice()));
// Then a bunch of errors because Ô is not an ascii-uppercase ô.
assert_eq!((Some(Token::Drole), "Drôle"),  (lex.next(), lex.slice()));
assert_eq!((Some(Token::Abc), "AaabbCC"),  (lex.next(), lex.slice()));
assert_eq!(None, lex.next());
```
For now, I prevented the user to use both `ascii_case` and `case` at the same time. This can be easily changed. …
> Add support for case insensitivity

- logos/src/source.rs
The `Chunk` implemented byte array length has extended to 32 in #142 .
> Update doc of Chunk

- logos-derive/Cargo.toml
- logos-derive/src/graph/range.rs
- logos-derive/src/graph/regex.rs
- logos/src/lib.rs
This removes the `utf8-ranges` dependency as this crate has been [deprecated](https://github.com/BurntSushi/utf8-ranges#readme) and now makes part of the `regex_syntax` crate.
> remove utf8-ranges dependency

- README.md
- logos/src/internal.rs
- logos/src/lib.rs
Implements the feature described in #235.
> Add `FilterResult` type

- logos/src/source.rs
with min-const-generics stable we can implement `Chunk` for all sizes and not just up to 32
fixes #141
> use const generics to implement Chunk for all array sizes

- logos-codegen/src/lib.rs
- logos-codegen/src/parser/mod.rs
- logos/Cargo.toml
- tests/tests/crate_.rs
Add a `crate` attribute similiar to what [serde](https://serde.rs/container-attrs.html#crate) has.
This allows logos proc-macro to be used and re-exported from another proc-macro without requiring the user to have logos in scope.
> Add logos(crate = "...") attribute

- README.md
- logos-codegen/src/generator/leaf.rs
- logos-codegen/src/leaf.rs
- logos-codegen/src/lib.rs
- logos-codegen/src/parser/mod.rs
- logos-codegen/src/parser/nested.rs
- logos/src/lib.rs
- tests/tests/advanced.rs
- tests/tests/callbacks.rs
- tests/tests/crate_.rs
- tests/tests/css.rs
- tests/tests/edgecase.rs
- tests/tests/ignore_case.rs
- tests/tests/properties.rs
- tests/tests/simple.rs
Follow up to the [discussion here](https://github.com/maciejhirsz/logos/pull/273#issuecomment-1445344527).
I'd be keen on some opinions on the syntax here. This might look a bit too magical right now, it's possible that `#[logos(skip regex("..."))]` would be better, so that `token` skips could also be an option.
> Added support for `#[logos(skip "...")]`

- logos/src/internal.rs
- tests/tests/callbacks.rs
With this patch, you can return tokens directly from callbacks--**but only** for unit variants. Closes #294.
```rust
#[derive(Logos, Debug, PartialEq)]
#[logos(skip r"[ \t\n\f]+")]
enum Token {
#[regex(r"[a-zA-Z]+", |_| Token::Text)]
#[regex(r"-?[0-9]+", |_| Token::Integer)]
#[regex(r"-?[0-9]+\.[0-9]+", |_| Token::Float)]
Text,
Integer,
Float,
}
```
> impl<T: Logos> CallbackResult for T

- .github/workflows/pages.yml
- README.md
- book/src/SUMMARY.md
- book/src/examples.md
- book/src/examples/brainfuck.md
- book/src/examples/json.md
- book/src/getting-started.md
- logos/Cargo.toml
- logos/examples/brainfuck.rs
- logos/examples/example.json
- logos/examples/hello_world.bf
- logos/examples/json.rs
- logos/src/lib.rs
This PR adds two examples of small projects that use Logos. I think it relevant to have those examples both in the handbook, as well as in the docs of the logos crates, this is why I added the scrape examples feature.
You can test it locally with `RUSTDOCFLAGS="--cfg docsrs" cargo +nightly doc --all-features -Zunstable-options -Zrustdoc-scrape-examples=examples --no-deps`.
It would be nice to fix the GitHub pages deployment (see https://github.com/maciejhirsz/logos/actions/runs/4693735567/jobs/8321101583) for future features, so it's easier for me and others to check that everything is fine.
Looking forward for your opinion on this PR :-)
> chore(book): adding examples

- logos-codegen/Cargo.toml
- logos-codegen/src/mir.rs
- tests/src/lib.rs
- tests/tests/binary.rs
Hi @maciejhirsz !
This PR follows what was discussed in #302.
I added a small check in `logos-codegen` to check for `.*` or `.+` patterns. When found, an error is raised with a helpful message that redirects to a solution.
I hope the implementation is correct (especially for non-utf8 cases and the fact that I also added a check for `.+`).
1. I had to move the doc tests from `tests/tests/binary.rs` to `tests/src/lib.rs` because I don't think they were ever executed;
2. I think that the pattern you mentioned in https://github.com/maciejhirsz/logos/issues/302#issuecomment-1521342541, namely `r"\([^)]*\)"`, is missing an `\` to escape the inner `)`;
3. and I added new tests that assert a compile error is raised for the given cases.
> chore(codegen): error to prevent undesired behavior

- book/src/extras.md
- logos/Cargo.toml
- logos/examples/extras.rs
Hey! This small PR adds an example for `Extras` and documents it in the book.
> chore(book): document extras

- logos/src/lexer.rs
I haven't done this before, I hope it is correct
> feat(lib): impl Clone for SpannedIter

- logos/Cargo.toml
- logos/src/lexer.rs
- logos/src/source.rs
- tests/src/lib.rs
This is required to write a `Source` impl for any type whose slice is a custom type and not a bare reference. For example, see [`ropey::RopeSlice`](https://docs.rs/ropey/latest/ropey/struct.RopeSlice.html).
Relates to #222.
> Use lifetime GAT for Source::Slice

- logos-codegen/src/lib.rs
- tests/tests/source.rs
Currently it isn't possible to use a custom `Source` with the `Logos` derive macro. Part of #222.
> Fix ignored source attribute

- tests/tests/source.rs
#332 and #333 weren't compatible, so `master` is currently broken. Sorry I forgot to warn about that @jeertmans!
> Update `Source` test for GAT `Slice`

- logos-codegen/Cargo.toml
> chore(deps): bump pretty-assertions to 1.4.0

- README.md
- book/src/attributes/logos.md
- book/src/callbacks.md
- book/src/contributing/setup.md
- book/src/getting-help.md
- book/src/getting-started.md
- book/src/intro.md
- examples/extras.rs
- logos-codegen/src/lib.rs
I missed the links to crates.io and else.
> fix(doc): reset logos2 to logos

- Cargo.toml
- logos-cli/Cargo.toml
- logos-codegen/Cargo.toml
- logos-codegen/src/lib.rs
- logos-codegen/src/macros.rs
- logos-derive/Cargo.toml
This adds a debug feature, similar to what Clap does, as requested by #379.
The current implementation only debugs a few parts of the code, and it may be interesting to add more debug messages in the different crates.
> chore(lib): add debug feature

- logos-codegen/src/generator/context.rs
- logos-codegen/src/generator/fork.rs
- src/internal.rs
- src/lexer.rs
- src/source.rs
- tests/tests/source.rs
These are just some small cleanups I came across while working on the remaining changes for #222.
> Cleanup unused Source features

- src/lexer.rs
- tests/tests/clone.rs
- tests/tests/string.rs
`Lexer::clone` shouldn't clone the inner `ManuallyDrop`, because doing so clones the inner value, which is moved out in `Lexer::next`.
This causes use-after-free if the lexer is cloned after the last-returned token is dropped, especially if the token contains an overridden implementation of `Clone` (such as `Rc`) that tries to read the dropped data.
It causes a memory leak if the token contains a heap-allocated value, because cloning makes a new allocation. This allocation is in the `ManuallyDrop` and it's guaranteed to be overridden before the call to `ManuallyDrop::take`, so it's never freed.
Another thing: https://github.com/maciejhirsz/logos/issues/263 (make `Lexer` implement `Copy`) probably should be added (referencing here because it looks like the issue has been forgotten).
> Fix `Lexer::clone` leak and UB + tests

- logos-codegen/src/graph/regex.rs
- tests/tests/edgecase.rs
fixes https://github.com/maciejhirsz/logos/issues/392
This PR changes the construction of the graph for a regex `Mir::Loop` when there is a `miss` path present. Given an input that essentially represents this control flow:
```mermaid
flowchart LR
start-->1
1((1))--a*-->2((2))
2((2))--then-->3((3))
1((1))--miss-->4((4))
```
we previously lowered it to a single loop and unconditionally merged the `then` and old `miss` arms into the new miss of the loop:
```mermaid
flowchart LR
start-->1((1))
1((1))--a-->1((1))
1((1))--_-->2((2))
2((2))--then-->3((3))
2((2))--miss-->4((4))
```
This lowering can lead to situations, where we incorrectly match `a` followed by `miss`, even though `a` must be followed by `then`.
This PR solves the issue by generating two separate paths for the first and other …
> fix(lib): correctly handle miss for loop in loop

- book/src/SUMMARY.md
- book/src/debugging.md
- logos-codegen/src/generator/mod.rs
- logos-codegen/src/lib.rs
I ran across [this comment](https://github.com/maciejhirsz/logos/issues/265#issuecomment-1939114278) while having some issues with `regex` support.  Thought this was beneficial information and wanted to try and include it in the book so it was a little more visible to people that may be trying to debug and understand how things are working
> chore(docs): Adds graph debug documentation to book

- logos-codegen/src/graph/regex.rs
Fixes #389. This *is* less efficient, but it's on codegen.
> fix(codegen/regex): allow vec growth on parse

- logos-codegen/src/graph/mod.rs
Fix for #427. I verified that the test fails in the same way as in the linked issue, when `to_be_bytes` is used instead, so this must have been the only portability issue that is detected by existing tests.
> fix(lib): generate same code on big-endian platforms

- book/src/callbacks.md
- src/internal.rs
- tests/tests/callbacks.rs
This makes it possible to return `Result<Skip>` from callbacks, which seems logical.
Here is an example usage:
```rust
use logos::{Lexer, Logos, Skip};
#[derive(Logos, Debug, PartialEq)]
#[logos(error = String)]
#[logos(skip r"\s*")] // Ignore this regex pattern between tokens
enum Token<'src> {
#[token("").ok_or_else(|| {
// this skips the rest of the input, as it all is part of the comment
lex.bump(rem.len());
"unterminated comment".to_string()
})?;
let open_pos = rem[..close_pos].find(" -->
<tag-name
<!--- unterminated 
/>
"#,
);
assert_eq!(lex.next(), Some(Ok(Token::TagOpen("tag-name"))));
assert_eq!(lex.next(), Some(Err("unterminated comment".to_string())));
assert_eq!(lex.next(), None);
}
```
> Support callbacks returning Result<Skip>

- logos-codegen/Cargo.toml
I confirmed that `cargo test --workspace` still works.
> Bump rstest to 0.23.0, the current release

- .github/workflows/rustlib.yml
- Cargo.toml
- logos-codegen/Cargo.toml
- logos-codegen/build.rs
- logos-codegen/src/generator/leaf.rs
Fixes https://github.com/maciejhirsz/logos/issues/434 by conditionally adding `+ use<'s>` to the implementation of the callback, but _only_ if on 1.82+
Additionally it adds tests for the MSRV and 1.82 to the CI.
> fix(lib): use precise capturing on 1.82+

- README.md
- RELEASE-PROCESS.md
- Put the release process in it's own file
- Removed extra whitespaces in a rust code block
> Minor readme improvments

- Cargo.toml
- book/src/getting-started.md
- logos-cli/Cargo.toml
- logos-derive/Cargo.toml
Release 0.14.3 as 0.15, as it bumped the MSRV, see #449.
> chore(release): bump to 0.15

- book/src/attributes/token_and_regex.md
Sorry, just reading through the book and the `#[regex`] bugged me a little...
> Fix #[regex] monospace formatting in 4.2 Token and Regex

- .github/workflows/coverage.yml
- .gitignore
- Cargo.toml
- fuzz/Cargo.toml
While adding tests for the safe-only code PR, I noticed that the code coverage action hasn't been able to complete successfully for a while.
Originally this was caused by rustfmt not being available in the container. So this installs it before running coverage.
Additionally, the new fuzz crate was interacting poorly with the other projects in the workspace, causing link errors for both the coverage action and when running `cargo build --workspace`. This is because afl crates must be built with `cargo afl build` so they can link properly. Excluding the fuzz crate from the workspace fixes both issues and also makes sure the fuzzing exports aren't inadvertently enabled on the codegen crate outside of running a fuzz.
> chore(ci): add rustfmt to codecov & exclude fuzz from workspace

- Cargo.toml
- logos-cli/Cargo.toml
- logos-codegen/Cargo.toml
- logos-derive/Cargo.toml
I came across the issue that the whole `mdbook` is included in the published crates during a dependency review, but `logos.png` is especially big and doesn't have to be included for everything to build.
This PR makes use of [`package.include`](https://doc.rust-lang.org/cargo/reference/manifest.html#the-exclude-and-include-fields) to not package these files.  
The excluded files based on the current version would be: `RELEASE-PROCESS.md`, `book/**`, `examples/**`, `logos.{svg,png}`, `release.toml`, `tests/**` and `logos-{codegen,cli}/tests/**`.
This reduces the size of almost all crates, but especially `logos` (note the change in units):
| crate | full without `package.include` | compressed | full with `package.include` | compressed |
|--------|--------|--------|--------|--------|
| …
> Use `package.include` in all published crates
